spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: 127.0.0.1
    port: 6379
    password: ssafy

logging:
  level:
    org.hibernate.SQL: info
